version: '3.5'
networks:
  default:
    driver: bridge
    ipam:
      driver: default

services:
  # mysql:
  #   image: mysql/mysql-server:${MYSQL_VERSION}
  #   container_name: mysql
  #   ports:
  #     - "${DB_PORT}:3306"
  #   volumes:
  #     - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
  #     - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
  #     - ${MYSQL_LOG_DIR}:/var/log/mysql/:rw
  #   restart: always
  #   networks:
  #     - default
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  #     MYSQL_ROOT_HOST: "${MYSQL_ROOT_HOST}"
  #     TZ: "$TZ"
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   - mysql
    ports:
      - ${APP_PORT}:${APP_PORT}
